site_name: Lightning
theme:
  name: readthedocs
nav:
    - Autoloader: autoloader.md
    - Autowire: autowire.md
    - Cache: cache.md
    - Collection: collection.md
    - Console: console.md
    - Container: container.md
    - Controller: controller.md
    - Criteria: criteria.md
    - DataMapper: datamapper.md
    - Dotenv: dotenv.md
    - Entity: entity.md
    - Event: event.md
    - Fixure: fixture.md
    - Formatter: formatter.md
    - Http:
      - Cookie: 'http/cookie.md'
      - Emitter: 'http/emitter.md'
      - Exception: 'http/exception.md'
      - ExceptionHandler: 'http/exception-handler.md'
      - Session: 'http/session.md'
    - Logger: logger.md
    - Message Queue: message-queue.md
    - Migration: migration.md
    - Query: query.md
    - QueryBuilder: query-builder.md
    - Repository: repository.md
    - Router: router.md
    - Service Object: service-object.md
    - Test Suite: test-suite.md
    - Translator: translator.md
    - View: view.md